/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorIndexRouteImport } from './routes/mentor.index'
import { Route as LearnerIndexRouteImport } from './routes/learner.index'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as MentorSubmissionsRouteImport } from './routes/mentor.submissions'
import { Route as MentorChallengesRouteImport } from './routes/mentor.challenges'
import { Route as MentorAnalyticsRouteImport } from './routes/mentor.analytics'
import { Route as LearnerSubmissionsRouteImport } from './routes/learner.submissions'
import { Route as LearnerProfileRouteImport } from './routes/learner.profile'
import { Route as LearnerLeaderboardRouteImport } from './routes/learner.leaderboard'
import { Route as LearnerChallengesRouteImport } from './routes/learner.challenges'
import { Route as CompanyTalentRouteImport } from './routes/company.talent'
import { Route as CompanyPipelineRouteImport } from './routes/company.pipeline'
import { Route as CompanyChallengesRouteImport } from './routes/company.challenges'
import { Route as MentorChallengesNewRouteImport } from './routes/mentor.challenges.new'
import { Route as LearnerChallengesIdRouteImport } from './routes/learner.challenges.$id'
import { Route as CompanyChallengesNewRouteImport } from './routes/company.challenges.new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorIndexRoute = MentorIndexRouteImport.update({
  id: '/mentor/',
  path: '/mentor/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerIndexRoute = LearnerIndexRouteImport.update({
  id: '/learner/',
  path: '/learner/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorSubmissionsRoute = MentorSubmissionsRouteImport.update({
  id: '/mentor/submissions',
  path: '/mentor/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorChallengesRoute = MentorChallengesRouteImport.update({
  id: '/mentor/challenges',
  path: '/mentor/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAnalyticsRoute = MentorAnalyticsRouteImport.update({
  id: '/mentor/analytics',
  path: '/mentor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerSubmissionsRoute = LearnerSubmissionsRouteImport.update({
  id: '/learner/submissions',
  path: '/learner/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerProfileRoute = LearnerProfileRouteImport.update({
  id: '/learner/profile',
  path: '/learner/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerLeaderboardRoute = LearnerLeaderboardRouteImport.update({
  id: '/learner/leaderboard',
  path: '/learner/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerChallengesRoute = LearnerChallengesRouteImport.update({
  id: '/learner/challenges',
  path: '/learner/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyTalentRoute = CompanyTalentRouteImport.update({
  id: '/company/talent',
  path: '/company/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPipelineRoute = CompanyPipelineRouteImport.update({
  id: '/company/pipeline',
  path: '/company/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyChallengesRoute = CompanyChallengesRouteImport.update({
  id: '/company/challenges',
  path: '/company/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorChallengesNewRoute = MentorChallengesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MentorChallengesRoute,
} as any)
const LearnerChallengesIdRoute = LearnerChallengesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LearnerChallengesRoute,
} as any)
const CompanyChallengesNewRoute = CompanyChallengesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CompanyChallengesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/company/challenges': typeof CompanyChallengesRouteWithChildren
  '/company/pipeline': typeof CompanyPipelineRoute
  '/company/talent': typeof CompanyTalentRoute
  '/learner/challenges': typeof LearnerChallengesRouteWithChildren
  '/learner/leaderboard': typeof LearnerLeaderboardRoute
  '/learner/profile': typeof LearnerProfileRoute
  '/learner/submissions': typeof LearnerSubmissionsRoute
  '/mentor/analytics': typeof MentorAnalyticsRoute
  '/mentor/challenges': typeof MentorChallengesRouteWithChildren
  '/mentor/submissions': typeof MentorSubmissionsRoute
  '/company/': typeof CompanyIndexRoute
  '/learner/': typeof LearnerIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/company/challenges/new': typeof CompanyChallengesNewRoute
  '/learner/challenges/$id': typeof LearnerChallengesIdRoute
  '/mentor/challenges/new': typeof MentorChallengesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/company/challenges': typeof CompanyChallengesRouteWithChildren
  '/company/pipeline': typeof CompanyPipelineRoute
  '/company/talent': typeof CompanyTalentRoute
  '/learner/challenges': typeof LearnerChallengesRouteWithChildren
  '/learner/leaderboard': typeof LearnerLeaderboardRoute
  '/learner/profile': typeof LearnerProfileRoute
  '/learner/submissions': typeof LearnerSubmissionsRoute
  '/mentor/analytics': typeof MentorAnalyticsRoute
  '/mentor/challenges': typeof MentorChallengesRouteWithChildren
  '/mentor/submissions': typeof MentorSubmissionsRoute
  '/company': typeof CompanyIndexRoute
  '/learner': typeof LearnerIndexRoute
  '/mentor': typeof MentorIndexRoute
  '/company/challenges/new': typeof CompanyChallengesNewRoute
  '/learner/challenges/$id': typeof LearnerChallengesIdRoute
  '/mentor/challenges/new': typeof MentorChallengesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/company/challenges': typeof CompanyChallengesRouteWithChildren
  '/company/pipeline': typeof CompanyPipelineRoute
  '/company/talent': typeof CompanyTalentRoute
  '/learner/challenges': typeof LearnerChallengesRouteWithChildren
  '/learner/leaderboard': typeof LearnerLeaderboardRoute
  '/learner/profile': typeof LearnerProfileRoute
  '/learner/submissions': typeof LearnerSubmissionsRoute
  '/mentor/analytics': typeof MentorAnalyticsRoute
  '/mentor/challenges': typeof MentorChallengesRouteWithChildren
  '/mentor/submissions': typeof MentorSubmissionsRoute
  '/company/': typeof CompanyIndexRoute
  '/learner/': typeof LearnerIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/company/challenges/new': typeof CompanyChallengesNewRoute
  '/learner/challenges/$id': typeof LearnerChallengesIdRoute
  '/mentor/challenges/new': typeof MentorChallengesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/company/challenges'
    | '/company/pipeline'
    | '/company/talent'
    | '/learner/challenges'
    | '/learner/leaderboard'
    | '/learner/profile'
    | '/learner/submissions'
    | '/mentor/analytics'
    | '/mentor/challenges'
    | '/mentor/submissions'
    | '/company/'
    | '/learner/'
    | '/mentor/'
    | '/company/challenges/new'
    | '/learner/challenges/$id'
    | '/mentor/challenges/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/company/challenges'
    | '/company/pipeline'
    | '/company/talent'
    | '/learner/challenges'
    | '/learner/leaderboard'
    | '/learner/profile'
    | '/learner/submissions'
    | '/mentor/analytics'
    | '/mentor/challenges'
    | '/mentor/submissions'
    | '/company'
    | '/learner'
    | '/mentor'
    | '/company/challenges/new'
    | '/learner/challenges/$id'
    | '/mentor/challenges/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/company/challenges'
    | '/company/pipeline'
    | '/company/talent'
    | '/learner/challenges'
    | '/learner/leaderboard'
    | '/learner/profile'
    | '/learner/submissions'
    | '/mentor/analytics'
    | '/mentor/challenges'
    | '/mentor/submissions'
    | '/company/'
    | '/learner/'
    | '/mentor/'
    | '/company/challenges/new'
    | '/learner/challenges/$id'
    | '/mentor/challenges/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CompanyChallengesRoute: typeof CompanyChallengesRouteWithChildren
  CompanyPipelineRoute: typeof CompanyPipelineRoute
  CompanyTalentRoute: typeof CompanyTalentRoute
  LearnerChallengesRoute: typeof LearnerChallengesRouteWithChildren
  LearnerLeaderboardRoute: typeof LearnerLeaderboardRoute
  LearnerProfileRoute: typeof LearnerProfileRoute
  LearnerSubmissionsRoute: typeof LearnerSubmissionsRoute
  MentorAnalyticsRoute: typeof MentorAnalyticsRoute
  MentorChallengesRoute: typeof MentorChallengesRouteWithChildren
  MentorSubmissionsRoute: typeof MentorSubmissionsRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  LearnerIndexRoute: typeof LearnerIndexRoute
  MentorIndexRoute: typeof MentorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/': {
      id: '/mentor/'
      path: '/mentor'
      fullPath: '/mentor/'
      preLoaderRoute: typeof MentorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/': {
      id: '/learner/'
      path: '/learner'
      fullPath: '/learner/'
      preLoaderRoute: typeof LearnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/submissions': {
      id: '/mentor/submissions'
      path: '/mentor/submissions'
      fullPath: '/mentor/submissions'
      preLoaderRoute: typeof MentorSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/challenges': {
      id: '/mentor/challenges'
      path: '/mentor/challenges'
      fullPath: '/mentor/challenges'
      preLoaderRoute: typeof MentorChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/analytics': {
      id: '/mentor/analytics'
      path: '/mentor/analytics'
      fullPath: '/mentor/analytics'
      preLoaderRoute: typeof MentorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/submissions': {
      id: '/learner/submissions'
      path: '/learner/submissions'
      fullPath: '/learner/submissions'
      preLoaderRoute: typeof LearnerSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/profile': {
      id: '/learner/profile'
      path: '/learner/profile'
      fullPath: '/learner/profile'
      preLoaderRoute: typeof LearnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/leaderboard': {
      id: '/learner/leaderboard'
      path: '/learner/leaderboard'
      fullPath: '/learner/leaderboard'
      preLoaderRoute: typeof LearnerLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/challenges': {
      id: '/learner/challenges'
      path: '/learner/challenges'
      fullPath: '/learner/challenges'
      preLoaderRoute: typeof LearnerChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/talent': {
      id: '/company/talent'
      path: '/company/talent'
      fullPath: '/company/talent'
      preLoaderRoute: typeof CompanyTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/pipeline': {
      id: '/company/pipeline'
      path: '/company/pipeline'
      fullPath: '/company/pipeline'
      preLoaderRoute: typeof CompanyPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/challenges': {
      id: '/company/challenges'
      path: '/company/challenges'
      fullPath: '/company/challenges'
      preLoaderRoute: typeof CompanyChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/challenges/new': {
      id: '/mentor/challenges/new'
      path: '/new'
      fullPath: '/mentor/challenges/new'
      preLoaderRoute: typeof MentorChallengesNewRouteImport
      parentRoute: typeof MentorChallengesRoute
    }
    '/learner/challenges/$id': {
      id: '/learner/challenges/$id'
      path: '/$id'
      fullPath: '/learner/challenges/$id'
      preLoaderRoute: typeof LearnerChallengesIdRouteImport
      parentRoute: typeof LearnerChallengesRoute
    }
    '/company/challenges/new': {
      id: '/company/challenges/new'
      path: '/new'
      fullPath: '/company/challenges/new'
      preLoaderRoute: typeof CompanyChallengesNewRouteImport
      parentRoute: typeof CompanyChallengesRoute
    }
  }
}

interface CompanyChallengesRouteChildren {
  CompanyChallengesNewRoute: typeof CompanyChallengesNewRoute
}

const CompanyChallengesRouteChildren: CompanyChallengesRouteChildren = {
  CompanyChallengesNewRoute: CompanyChallengesNewRoute,
}

const CompanyChallengesRouteWithChildren =
  CompanyChallengesRoute._addFileChildren(CompanyChallengesRouteChildren)

interface LearnerChallengesRouteChildren {
  LearnerChallengesIdRoute: typeof LearnerChallengesIdRoute
}

const LearnerChallengesRouteChildren: LearnerChallengesRouteChildren = {
  LearnerChallengesIdRoute: LearnerChallengesIdRoute,
}

const LearnerChallengesRouteWithChildren =
  LearnerChallengesRoute._addFileChildren(LearnerChallengesRouteChildren)

interface MentorChallengesRouteChildren {
  MentorChallengesNewRoute: typeof MentorChallengesNewRoute
}

const MentorChallengesRouteChildren: MentorChallengesRouteChildren = {
  MentorChallengesNewRoute: MentorChallengesNewRoute,
}

const MentorChallengesRouteWithChildren =
  MentorChallengesRoute._addFileChildren(MentorChallengesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CompanyChallengesRoute: CompanyChallengesRouteWithChildren,
  CompanyPipelineRoute: CompanyPipelineRoute,
  CompanyTalentRoute: CompanyTalentRoute,
  LearnerChallengesRoute: LearnerChallengesRouteWithChildren,
  LearnerLeaderboardRoute: LearnerLeaderboardRoute,
  LearnerProfileRoute: LearnerProfileRoute,
  LearnerSubmissionsRoute: LearnerSubmissionsRoute,
  MentorAnalyticsRoute: MentorAnalyticsRoute,
  MentorChallengesRoute: MentorChallengesRouteWithChildren,
  MentorSubmissionsRoute: MentorSubmissionsRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  LearnerIndexRoute: LearnerIndexRoute,
  MentorIndexRoute: MentorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
